services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    build:
      dockerfile: dev.Dockerfile
      args:
        UID: 1000
        GID: 1000
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

networks:
  default:
    name: hyperf-skeleton
